{
 "title": "Links de internet (Speedtest, ICMP, Jitter, Loss, Response time)",
 "tags": [
  "DNS",
  "Jitter",
  "Links de Internet",
  "Link",
  "Internet",
  "PING",
  "ICMP",
  "Algar",
  "Vivo"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Vivo - Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Ping Status to 8.8.8.8 via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - HTTP GET",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "HTTP GET Google from https://www.google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - Status HTTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "HTTP Status to https://www.google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - Loss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Loss to 8.8.8.8 via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - Jitter/Latência",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": { "filter": "Jitter SpeedTest ens256 - Vivo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": {
      "filter": "Latência SpeedTest ens256 - Vivo"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar - Jitter/Latência",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Jitter SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Latência SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo Down/Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "$Network" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": {
      "filter": "Download SpeedTest ens256 - Vivo"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "$Network" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": { "filter": "Upload SpeedTest ens256 - Vivo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Algar - Down/Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "$Network" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Download SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "$Network" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Upload SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Algar - Disponibilidade",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Ping Status to 8.8.8.8 via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar - HTTP GET",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "HTTP GET Google from https://www.google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar -Status HTTP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "HTTP Status to https://www.google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar - Loss",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Loss to 8.8.8.8 via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Perda de pacotes - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Loss to 8.8.8.8 via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Latência - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Response Time to 8.8.8.8 via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Vivo - Jitter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": { "filter": "Jitter SpeedTest ens256 - Vivo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": {
      "filter": "Download SpeedTest ens256 - Vivo"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens256 - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS SAAN - 610000150135898"
     },
     "item": { "filter": "Upload SpeedTest ens256 - Vivo" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Perda de pacotes - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Loss to 8.8.8.8 via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Latência - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "ICMP Response Time to 8.8.8.8 via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Algar - Jitter",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Jitter SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Download SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Speedtest - ens224 - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS SAAN - LP:08524170"
     },
     "item": {
      "filter": "Upload SpeedTest ens224 - Algar"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Vivo - DNS Check",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Check to google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar - DNS Check",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Check to google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - DNS Status Flag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Status Flag for google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - DNS Status Flag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Status Flag for google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - DNS IP(s) resolved",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS IP(s) resolved for google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar - DNS IP(s) resolved",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS IP(s) resolved for google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Vivo - DNS Query time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Query time to google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Algar - DNS Query time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Query time to google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "DNS Query time - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Query time to google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "DNS Query time - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS Query time to google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "DNS TTL - VIVO 1GB - SAIDA PRINCIPAL DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "VIVO 610000150135898 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS TTL for google.com via ens256 - Vivo 610000150135898"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "DNS TTL - ALGAR - 1GB - LINK AWS / BCKP SAIDA DE INTERNET USUARIOS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "ICMP" },
     "evaltype": "0",
     "group": { "filter": "Links de Internet - DNS" },
     "host": {
      "filter": "Algar LP08524170 - Teste DNS 8.8.8.8 - Google.com"
     },
     "item": {
      "filter": "DNS TTL for google.com via ens224 - Algar 08524170"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  }
 ]
}